### ISSUE TITLE
API to change between UEFI boot mode and legacy boot mode does not work

### ISSUE THREAD

**Issue by ankit-timbadia** [lenovo/python-redfish-lenovo#22]
Using the following API does not change the boot mode from UEFI boot mode to legacy let me know if any more details are needed.

Following is the response received:

root@productionserver:/home/ankit.timbadia/LENOVO/LENOVO/python-redfish-lenovo/examples# python set_bios_bootmode_legacy.py
"set bios bootmode legacy successful"

Checking the value applied shows:

root@productionserver:/home/ankit.timbadia/LENOVO/LENOVO/python-redfish-lenovo/examples# python get_bios_bootmode.py
{
  "BootSourceOverrideMode": "Legacy"
}

Did a force restart/reboot of the server still the changes are not applied
Let me know if any other details are required. 

![image](https://user-images.githubusercontent.com/45550942/59663159-10a33c80-91cc-11e9-99c0-f4970d49008c.png)

Thanks,
Ankit Timbadia

**Comment by panyy3** [comment]
When looking into the script, I find out that the script just change boot once target's boot mode, not system's boot mode. As system's boot mode is expected instead of boot once's boot mode, I will update the script to system's boot mode in this week. Thanks for your report. And sorry for this issue.

Before updating, please use set_bios_attribute.py as below to change system's boot mode.
#python set_bios_attribute.py --name BootModes_SystemBootMode --value LegacyMode

**Comment by ankit-timbadia** [comment]
Awesome works now, thanks for the quick fix @panyy3 :)
