### ISSUE TITLE
Setting for Complex Password Required

### ISSUE THREAD

**Issue by Tic2k** [lenovo/python-redfish-lenovo#34]
Hello,
while preparing a script to change some Account Service Settings, i was not able to find the Setting inside the Account Service (and other Redfish paths) for the Button (in the WebGUI) "Complex Password Required"

Somebody knows where i can find this setting?

regards

**Comment by renxulei** [comment]
@Tic2k Unfortunately, so far no way to set this via Redfish. DMTF Redfish standard schema does not define the property to enable/disable complex password, and Lenovo Redfish OEM implementation have not supported this also because it is not preferred to disable complex password (default is enabled). Could you let me know what kind of use cases to make you have to change this setting?

**Comment by Tic2k** [comment]
Thank u for this Information.
We are providing large Numbers of Server (+configuration) in Costumer Datacenters and most of the time we have to disable USERID and to create a new "Handover" User. And these Users does not match all the Complex Password requirements everytime.

**Comment by renxulei** [comment]
@Tic2k thank you for your information. I will transfer your request to development team and co-work with them to see how to add your request in Redfish implementation. Any progress, will let you know.

**Comment by Tic2k** [comment]
@renxulei Thank u, that would be great.

**Comment by JesseDarr** [comment]
Is there any update on this?  I'm using the powershell module instead, but I'm also look to change the Complex Password setting.

**Comment by renxulei** [comment]
@JesseDarr Sorry for late response, I spent some time to figure out one workaround. Because disabling complex password is not preferred, new Redfish schema does not support this requirement. But I added specific handling in _lenovo_set_bmc_user_global.py_ to disable complex password setting via https request (not Redfish), not sure if this can meet your needs. below is one example, could you try this?
> _python lenovo_set_bmc_user_global.py -i IP -u USERID -p PASSWORD --ComplexPassword 0_
