### ISSUE TITLE
Mount Virtual Media

### ISSUE THREAD

**Issue by dougjdouma** [lenovo/python-redfish-lenovo#9]
I'm using the mount_virtual_media.py example to attempt to mount media on an XCC RedFish compliant Lenovo system (SD530 - MT 7X21).

When I attempt to mount the media, I get an error that says "Up to 4 files can be concurrently mounted to the server by the BMC."  This is because the call to the virtual media url returns no members as I don't have any media mounted at the moment.  Any ideas on how to work around this?  I tried a POST with the body `{"Image": media_uri, "WriteProtected": bool(writeprotocol), "Inserted": bool(inserted)}` to `/redfish/v1/Managers/1/VirtualMedia/EXT2,` but I got a 404 back

**Comment by renxulei** [comment]
@amuodd thank you very much to report this issue. 
Current mount_virtual_media.py only works on the latest XCC Firmware of lenovo, XCC version should be 2.50 and above. in this version, there are predefined members under "VirtualMedia". you can check "version" property of the URI below:
https://ip/redfish/v1/UpdateService/FirmwareInventory/BMC-Primary
if your version is lower than it, there is no predefined members under "VirtualMedia", I think this maybe major cause of the issue you mentioned. you can try the scripts below, which are developed before only for old version of XCC.  From now on, I will merge the codes into one script to support both the latest Firmware and old firmware, once it is completed, I will let you know.
=======================
Mount:
https://github.com/renxulei/python-redfish-lenovo/blob/lenovo-internal-functions/examples/lenovo_mount_virtual_media_from_network.py 
https://github.com/renxulei/python-redfish-lenovo/blob/lenovo-internal-functions/examples/lenovo_mount_virtual_media_from_rdoc.py 

  Example:  10.245.39.209 is the IP address of SFTP server or HTTP server. Upload is the path under which efiboot.img is put.
>python lenovo_mount_virtual_media_from_network.py -i 10.245.39.234 --isoname efiboot.img --fsprotocol SFTP --fsip 10.245.39.209 --fsdir upload
>python lenovo_mount_virtual_media_from_network.py -i 10.245.39.234 --isoname efiboot.img --fsprotocol HTTP --fsip 10.245.39.209 --fsdir upload
  For rdoc, it is similar with network, except image size should be less than 50MB.

======================
Umount:
https://github.com/renxulei/python-redfish-lenovo/blob/lenovo-internal-functions/examples/lenovo_umount_all_virtual_media_from_network.py 
(Note: ALL media from network will be unmounted because XCC action cannot support unmounting 1 media)
https://github.com/renxulei/python-redfish-lenovo/blob/lenovo-internal-functions/examples/lenovo_umount_virtual_media_from_rdoc.py 

if you still have issues, feel free to let me know, thanks!

**Comment by samerhaj** [comment]
@renxulei it would be helpful to add these notes as comments in the python files

**Comment by renxulei** [comment]
@samerhaj I added the comments in python files to describe XCC version dependency.

**Comment by samerhaj** [comment]
@dougjdouma  can you please confirm if updating to the latest XCC (ver 2.5) and using https://github.com/lenovo/python-redfish-lenovo worked for you? I confirmed that it works on my system

**Comment by timeu** [comment]
I get following error when I run `python mount_virtual_media.py --inserted --fsprotocol HTTP --image tinycorelinux.net/12.x/x86/release/TinyCore-12.0.iso`:

```
Url '/redfish/v1/Managers/1/VirtualMedia/EXT1' response Error code 400
error_message: The request could not be completed due to a conflict with the current state of the resource
```

This is for a ThinkSystem SD530 with XCC/BMCversion V4.00 (Build ID: TEI3A4L)

**Comment by panyy3** [comment]
Hi timeu, The error you met is related to an issue about inserted parameter. I am sorry for it and thanks for report this issue. I have created an pull to fix it. Please refer to https://github.com/lenovo/python-redfish-lenovo/pull/170

**Comment by timeu** [comment]
@panyy3 : Thanks for the quick fix. I tried your PR however unfortunately I still get the same error:

```
(redfish) [[dev]stack@uc examples]$ git branch
* (HEAD detached at panyy3/fix-mount-with-inserted-none)
  master

(redfish) [[dev]stack@uc examples]$ python mount_virtual_media.py --fsprotocol HTTP --image tinycorelinux.net/12.x/x86/release/TinyCore-12.0.iso
Url '/redfish/v1/Managers/1/VirtualMedia/EXT1' response Error code 400 
error_message: The service failed to establish a connection with the URI http:///tinycorelinux.net/12.x/x86/release/TinyCore-12.0.iso.
```

**Comment by timeu** [comment]
I tried also the library https://github.com/DMTF/Redfish-Tacklebox by running: `rf_virtual_media.py -u USERNAME -p xxxx -r https://10.100.66.71 insert --image http://tinycorelinux.net/12.x/x86/release/TinyCore-12.0.iso`
and I get following error:
```
Traceback (most recent call last):
  File "/home/stack/.venv/redfish/bin/rf_virtual_media.py", line 43, in <module>
    redfish_utilities.insert_virtual_media( redfish_obj, args.image, args.system, args.id, args.mediatypes, args.notinserted, args.writable )
  File "/home/stack/.venv/redfish/lib64/python3.6/site-packages/redfish_utilities/systems.py", line 346, in insert_virtual_media
    verify_response( response )
  File "/home/stack/.venv/redfish/lib64/python3.6/site-packages/redfish_utilities/messages.py", line 71, in verify_response
    raise RedfishOperationFailedError( "Operation failed: HTTP {}\n{}".format( response.status, exception_string ) )
redfish_utilities.messages.RedfishOperationFailedError: Operation failed: HTTP 400
A general error has occurred. See ExtendedInfo for more information.
The property Image is a read only property and cannot be assigned a value.
```

**Comment by panyy3** [comment]
Hi Timeu,  "The service failed to establish a connection with the URI http:///tinycorelinux.net/12.x/x86/release/TinyCore-12.0.iso." error is caused by that server BMC cannot recognize domain name withou DNS configured. You can use lenovo_set_bmc_dns.py to set DNS as below. Or set it on webUI
Ex. #python3 lenovo_set_bmc_dns.py --enabled 1 --dnsserver 10.103.62.178

**Comment by panyy3** [comment]
Note: 10.103.62.178 is just an example. You should use your correct DNS server.

**Comment by timeu** [comment]
@panyy3 : Ah thanks for the hint. I saw response code 400 and assumed that it was the same error. But I should have looked at the error message more closely. I think in our case the issue is that the XCC/BMC can not reach out because they are in a private network. I tried it with an HTTP server that is reachable and it works now fine:

```
(redfish) [[dev]stack@uc examples]$ python mount_virtual_media.py --fsprotocol HTTP --image 10.100.72.227:8088/test.iso
"IP:PORT/test.iso' mount successfully"
```
